# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stats.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(1049, 803)
        widget.setStyleSheet("QWidget {\n"
"    background-image: url(:/try/bg.jpg);  /* 使用资源路径 */\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"    background-size: cover;  /* 填充整个窗口 */\n"
"}")
        self.line = QtWidgets.QFrame(widget)
        self.line.setGeometry(QtCore.QRect(9, 9, 1279, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.spinBox = QtWidgets.QSpinBox(widget)
        self.spinBox.setGeometry(QtCore.QRect(660, 590, 191, 21))
        self.spinBox.setMaximum(10000)
        self.spinBox.setObjectName("spinBox")
        self.widget = QtWidgets.QWidget(widget)
        self.widget.resize(231, 51)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.comboBox = QtWidgets.QComboBox(self.widget)
        self.comboBox.setStyleSheet("   QComboBox {\n"
"        background-color: #4CAF50;\n"
"        border: 1px solid #ccc;\n"
"        padding: 5px;\n"
"font: bold 14px \"微软雅黑\";  /* 字体 */\n"
"color:white;\n"
"    }\n"
"  ")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50; /* 按钮背景颜色 */\n"
"    color: white;             /* 按钮文字颜色 */\n"
"    border: none;             /* 移除边框 */\n"
"    padding: 10px 20px;       /* 内边距 */\n"
"    text-align: center;       /* 文本居中 */\n"
"    font-size: 16px;          /* 字体大小 */\n"
"    border-radius: 5px;       /* 圆角 */\n"
"font: bold 14px \"微软雅黑\";  /* 字体 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049; /* 鼠标悬停时的背景颜色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3e8e41; /* 按钮按下时的背景颜色 */\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_2.addWidget(self.pushButton_4)
        self.label_2 = QtWidgets.QLabel(widget)
        self.label_2.setGeometry(QtCore.QRect(660, 550, 71, 31))
        self.label_2.setStyleSheet("    QLabel {\n"
"        color: white;              /* 文字颜色 */\n"
"        background-color: #FFFF00;   /* 背景色 */\n"
"        border: 2px solid #0000FF;   /* 边框 */\n"
"        border-radius: 10px;         /* 圆角半径 */\n"
"        padding: 5px;                /* 内边距 */\n"
"        font: bold 14px \"微软雅黑\";  /* 字体 */\n"
"    }")
        self.label_2.setObjectName("label_2")
        self.plotWidget1 = QtWidgets.QWidget(widget)
        self.plotWidget1.setGeometry(QtCore.QRect(670, 70, 371, 201))
        self.plotWidget1.setObjectName("plotWidget1")
        self.label_3 = QtWidgets.QLabel(widget)
        self.label_3.setGeometry(QtCore.QRect(670, 40, 71, 31))
        self.label_3.setStyleSheet("    QLabel {\n"
"        color: white;              /* 文字颜色 */\n"
"        background-color: #FFFF00;   /* 背景色 */\n"
"        border: 2px solid #0000FF;   /* 边框 */\n"
"        border-radius: 10px;         /* 圆角半径 */\n"
"        padding: 5px;                /* 内边距 */\n"
"        font: bold 14px \"微软雅黑\";  /* 字体 */\n"
"    }")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(widget)
        self.label_4.setGeometry(QtCore.QRect(670, 270, 71, 31))
        self.label_4.setStyleSheet("    QLabel {\n"
"        color: white;              /* 文字颜色 */\n"
"        background-color: #FFFF00;   /* 背景色 */\n"
"        border: 2px solid #0000FF;   /* 边框 */\n"
"        border-radius: 10px;         /* 圆角半径 */\n"
"        padding: 5px;                /* 内边距 */\n"
"        font: bold 14px \"微软雅黑\";  /* 字体 */\n"
"    }")
        self.label_4.setObjectName("label_4")
        self.plotWidget2 = QtWidgets.QWidget(widget)
        self.plotWidget2.setGeometry(QtCore.QRect(670, 300, 371, 221))
        self.plotWidget2.setObjectName("plotWidget2")
        self.label_5 = QtWidgets.QLabel(widget)
        self.label_5.setGeometry(QtCore.QRect(660, 680, 71, 31))
        self.label_5.setStyleSheet("    QLabel {\n"
"        color: white;              /* 文字颜色 */\n"
"        background-color: #FFFF00;   /* 背景色 */\n"
"        border: 2px solid #0000FF;   /* 边框 */\n"
"        border-radius: 10px;         /* 圆角半径 */\n"
"        padding: 5px;                /* 内边距 */\n"
"        font: bold 14px \"微软雅黑\";  /* 字体 */\n"
"    }")
        self.label_5.setObjectName("label_5")
        self.widget1 = QtWidgets.QWidget(widget)
        self.widget1.setGeometry(QtCore.QRect(10, 60, 151, 341))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_9 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_9.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50; /* 按钮背景颜色 */\n"
"    color: white;             /* 按钮文字颜色 */\n"
"    border: none;             /* 移除边框 */\n"
"    padding: 10px 20px;       /* 内边距 */\n"
"    text-align: center;       /* 文本居中 */\n"
"    font-size: 16px;          /* 字体大小 */\n"
"    border-radius: 5px;       /* 圆角 */\n"
"    font: bold 14px \"微软雅黑\";  /* 字体 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049; /* 鼠标悬停时的背景颜色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3e8e41; /* 按钮按下时的背景颜色 */\n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_4.addWidget(self.pushButton_9)
        self.pushButton_8 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50; /* 按钮背景颜色 */\n"
"    color: white;             /* 按钮文字颜色 */\n"
"    border: none;             /* 移除边框 */\n"
"    padding: 10px 20px;       /* 内边距 */\n"
"    text-align: center;       /* 文本居中 */\n"
"    font-size: 16px;          /* 字体大小 */\n"
"    border-radius: 5px;       /* 圆角 */\n"
"font: bold 14px \"微软雅黑\";  /* 字体 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049; /* 鼠标悬停时的背景颜色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3e8e41; /* 按钮按下时的背景颜色 */\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_4.addWidget(self.pushButton_8)
        self.pushButton_10 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_10.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50; /* 按钮背景颜色 */\n"
"    color: white;             /* 按钮文字颜色 */\n"
"    border: none;             /* 移除边框 */\n"
"    padding: 10px 20px;       /* 内边距 */\n"
"    text-align: center;       /* 文本居中 */\n"
"    font-size: 16px;          /* 字体大小 */\n"
"    border-radius: 5px;       /* 圆角 */\n"
"font: bold 14px \"微软雅黑\";  /* 字体 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049; /* 鼠标悬停时的背景颜色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3e8e41; /* 按钮按下时的背景颜色 */\n"
"}")
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_4.addWidget(self.pushButton_10)
        self.pushButton_7 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50; /* 按钮背景颜色 */\n"
"    color: white;             /* 按钮文字颜色 */\n"
"    border: none;             /* 移除边框 */\n"
"    padding: 10px 20px;       /* 内边距 */\n"
"    text-align: center;       /* 文本居中 */\n"
"    font-size: 16px;          /* 字体大小 */\n"
"    border-radius: 5px;       /* 圆角 */\n"
"font: bold 14px \"微软雅黑\";  /* 字体 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049; /* 鼠标悬停时的背景颜色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3e8e41; /* 按钮按下时的背景颜色 */\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_4.addWidget(self.pushButton_7)
        self.pushButton = QtWidgets.QPushButton(self.widget1)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50; /* 按钮背景颜色 */\n"
"    color: white;             /* 按钮文字颜色 */\n"
"    border: none;             /* 移除边框 */\n"
"    padding: 10px 20px;       /* 内边距 */\n"
"    text-align: center;       /* 文本居中 */\n"
"    font-size: 16px;          /* 字体大小 */\n"
"    border-radius: 5px;       /* 圆角 */\n"
"font: bold 14px \"微软雅黑\";  /* 字体 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049; /* 鼠标悬停时的背景颜色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3e8e41; /* 按钮按下时的背景颜色 */\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_4.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50; /* 按钮背景颜色 */\n"
"    color: white;             /* 按钮文字颜色 */\n"
"    border: none;             /* 移除边框 */\n"
"    padding: 10px 20px;       /* 内边距 */\n"
"    text-align: center;       /* 文本居中 */\n"
"    font-size: 16px;          /* 字体大小 */\n"
"    border-radius: 5px;       /* 圆角 */\n"
"font: bold 14px \"微软雅黑\";  /* 字体 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049; /* 鼠标悬停时的背景颜色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3e8e41; /* 按钮按下时的背景颜色 */\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_4.addWidget(self.pushButton_2)
        self.pushButton_5 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50; /* 按钮背景颜色 */\n"
"    color: white;             /* 按钮文字颜色 */\n"
"    border: none;             /* 移除边框 */\n"
"    padding: 10px 20px;       /* 内边距 */\n"
"    text-align: center;       /* 文本居中 */\n"
"    font-size: 16px;          /* 字体大小 */\n"
"    border-radius: 5px;       /* 圆角 */\n"
"font: bold 14px \"微软雅黑\";  /* 字体 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049; /* 鼠标悬停时的背景颜色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3e8e41; /* 按钮按下时的背景颜色 */\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_4.addWidget(self.pushButton_5)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.line_2 = QtWidgets.QFrame(self.widget1)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_4.addWidget(self.line_2)
        self.label = QtWidgets.QLabel(widget)
        self.label.setGeometry(QtCore.QRect(160, 40, 491, 481))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/try/map.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(widget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 545, 641, 251))
        self.textBrowser.setStyleSheet("QTextBrowser {\n"
"    background-color: black;\n"
"    color: white;\n"
"    font-family: Arial;\n"
"    font-size: 14px;\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"}")
        self.textBrowser.setObjectName("textBrowser")
        self.lineEdit = QtWidgets.QLineEdit(widget)
        self.lineEdit.setGeometry(QtCore.QRect(660, 720, 145, 28))
        self.lineEdit.setStyleSheet("    QLineEdit {\n"
"        color: white;              /* 文字颜色 */\n"
"        background-color: #F5F5F5;  /* 背景色 */\n"
"        border: 1px solid #CCCCCC;    /* 边框 */\n"
"        border-radius: 4px;          /* 圆角 */\n"
"        padding: 5px 10px;           /* 内边距（上下 左右） */\n"
"        font-size: 14px;             /* 字体大小 */\n"
"\n"
"    }")
        self.lineEdit.setObjectName("lineEdit")
        self.line.raise_()
        self.comboBox.raise_()
        self.pushButton_4.raise_()
        self.spinBox.raise_()
        self.label_2.raise_()
        self.plotWidget1.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.plotWidget2.raise_()
        self.label_5.raise_()

        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "移动卫星通信系统"))
        self.spinBox.setToolTip(_translate("widget", "<html><head/><body><p>采样率</p></body></html>"))
        self.comboBox.setItemText(0, _translate("widget", "语音信号"))
        self.comboBox.setItemText(1, _translate("widget", "正弦波模拟"))
        self.comboBox.setItemText(2, _translate("widget", "方波"))
        self.comboBox.setItemText(3, _translate("widget", "三角波"))
        self.pushButton_4.setText(_translate("widget", "输入"))
        self.label_2.setText(_translate("widget", "采样率"))
        self.label_3.setText(_translate("widget", "输入信号"))
        self.label_4.setText(_translate("widget", "输出信号"))
        self.label_5.setText(_translate("widget", "文件选择"))
        self.pushButton_9.setText(_translate("widget", "AD—PCM编码"))
        self.pushButton_8.setText(_translate("widget", "Turbo编码"))
        self.pushButton_10.setText(_translate("widget", "调制"))
        self.pushButton_7.setText(_translate("widget", "协议"))
        self.pushButton.setText(_translate("widget", "解调"))
        self.pushButton_2.setText(_translate("widget", "DA"))
        self.pushButton_5.setText(_translate("widget", "噪声分析"))
        self.textBrowser.setHtml(_translate("widget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:14px; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:12pt;\">显示当前状态</span></p></body></html>"))
        self.lineEdit.setText(_translate("widget", "speech.wav"))
import code_rc
import resource_rc
